name: Demo Workflow

on: [push]

jobs:
  first_self_hosted_job:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run any command on the self hosted machine
        run: echo "Hello from Pratham's machine"
